# SPDX-License-Identifier: GPL-2.0
# VIA/Wondermedia pinctrl support

obj-$(CONFIG_PINCTRL_TSXBAR)	+= pinctrl-tsxbar.o
obj-$(CONFIG_PINCTRL_TS9370)	+= pinctrl-ts9370.o
obj-$(CONFIG_PINCTRL_TS9390)	+= pinctrl-ts9390.o
