#
# Makefile for Invensense inv-mpu-iio device.
# Makefile modified for vanilla 4.4x kernel
#

obj-$(CONFIG_INV_MPU_IIO) += inv_mpu_core.o inv_mpu_ring.o inv_mpu_trigger.o inv_mpu_misc.o inv_mpu3050_iio.o dmpDefaultMPU6050.o inv_slave_compass.o inv_slave_pressure.o

